<?php

return [
    'attachtypes' => [
        [
            'atid' => '1',
            'name' => 'ZIP File',
            'mimetype' => 'application/zip',
            'extension' => 'zip',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/zip.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '2',
            'name' => 'JPG Image',
            'mimetype' => 'image/jpeg',
            'extension' => 'jpg',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/image.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '1',
        ],
        [
            'atid' => '3',
            'name' => 'Text Document',
            'mimetype' => 'text/plain',
            'extension' => 'txt',
            'maxsize' => '200',
            'icon' => 'images/attachtypes/txt.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '4',
            'name' => 'GIF Image',
            'mimetype' => 'image/gif',
            'extension' => 'gif',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/image.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '1',
        ],
        [
            'atid' => '5',
            'name' => 'Adobe Photoshop File',
            'mimetype' => 'application/x-photoshop',
            'extension' => 'psd',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/psd.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '6',
            'name' => 'PHP File',
            'mimetype' => 'application/x-httpd-php',
            'extension' => 'php',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/php.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '7',
            'name' => 'PNG Image',
            'mimetype' => 'image/png',
            'extension' => 'png',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/image.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '1',
        ],
        [
            'atid' => '8',
            'name' => 'Microsoft Word Document',
            'mimetype' => 'application/msword',
            'extension' => 'doc',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/doc.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '9',
            'name' => 'HTM File',
            'mimetype' => 'text/html',
            'extension' => 'htm',
            'maxsize' => '100',
            'icon' => 'images/attachtypes/html.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '10',
            'name' => 'HTML File',
            'mimetype' => 'text/html',
            'extension' => 'html',
            'maxsize' => '100',
            'icon' => 'images/attachtypes/html.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '11',
            'name' => 'JPEG Image',
            'mimetype' => 'image/jpeg',
            'extension' => 'jpeg',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/image.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '1',
        ],
        [
            'atid' => '12',
            'name' => 'GZIP Compressed File',
            'mimetype' => 'application/x-gzip',
            'extension' => 'gz',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/tar.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '13',
            'name' => 'TAR Compressed File',
            'mimetype' => 'application/x-tar',
            'extension' => 'tar',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/tar.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '14',
            'name' => 'CSS Stylesheet',
            'mimetype' => 'text/css',
            'extension' => 'css',
            'maxsize' => '100',
            'icon' => 'images/attachtypes/css.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '15',
            'name' => 'Adobe Acrobat PDF',
            'mimetype' => 'application/pdf',
            'extension' => 'pdf',
            'maxsize' => '2048',
            'icon' => 'images/attachtypes/pdf.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '16',
            'name' => 'Bitmap Image',
            'mimetype' => 'image/bmp',
            'extension' => 'bmp',
            'maxsize' => '500',
            'icon' => 'images/attachtypes/image.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '17',
            'name' => 'Microsoft Word 2007 Document',
            'mimetype' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'extension' => 'docx',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/doc.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '18',
            'name' => 'Microsoft Excel Document',
            'mimetype' => 'application/vnd.ms-excel',
            'extension' => 'xls',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/xls.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '19',
            'name' => 'Microsoft Excel 2007 Document',
            'mimetype' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'extension' => 'xlsx',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/xls.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '20',
            'name' => 'Microsoft PowerPoint Document',
            'mimetype' => 'application/vnd.ms-powerpoint',
            'extension' => 'ppt',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/ppt.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
        [
            'atid' => '21',
            'name' => 'Microsoft PowerPoint 2007 Document',
            'mimetype' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'extension' => 'pptx',
            'maxsize' => '1024',
            'icon' => 'images/attachtypes/ppt.png',
            'enabled' => '1',
            'groups' => '-1',
            'forums' => '-1',
            'avatarfile' => '0',
        ],
    ],
    'calendars' => [
        [
            'name' => 'Default Calendar',
            'disporder' => '1',
            'startofweek' => '0',
            'showbirthdays' => '1',
            'eventlimit' => '4',
            'moderation' => '0',
            'allowhtml' => '0',
            'allowmycode' => '1',
            'allowimgcode' => '1',
            'allowvideocode' => '1',
            'allowsmilies' => '1',
        ],
    ],
    'forums' => [
        [
            'fid' => '1',
            'name' => 'My Category',
            'description' => '',
            'linkto' => '',
            'type' => 'c',
            'pid' => '0',
            'parentlist' => '1',
            'disporder' => '1',
            'active' => '1',
            'open' => '1',
            'threads' => '0',
            'posts' => '0',
            'lastpost' => '0',
            'lastposter' => '0',
            'lastposttid' => '0',
            'allowhtml' => '0',
            'allowmycode' => '1',
            'allowsmilies' => '1',
            'allowimgcode' => '1',
            'allowvideocode' => '1',
            'allowpicons' => '1',
            'allowtratings' => '1',
            'usepostcounts' => '1',
            'usethreadcounts' => '1',
            'password' => '',
            'showinjump' => '1',
            'style' => '0',
            'overridestyle' => '0',
            'rulestype' => '0',
            'rulestitle' => '',
            'rules' => '',
        ],
        [
            'fid' => '2',
            'name' => 'My Forum',
            'description' => '',
            'linkto' => '',
            'type' => 'f',
            'pid' => '1',
            'parentlist' => '1,2',
            'disporder' => '1',
            'active' => '1',
            'open' => '1',
            'threads' => '0',
            'posts' => '0',
            'lastpost' => '0',
            'lastposter' => '0',
            'lastposttid' => '0',
            'allowhtml' => '0',
            'allowmycode' => '1',
            'allowsmilies' => '1',
            'allowimgcode' => '1',
            'allowvideocode' => '1',
            'allowpicons' => '1',
            'allowtratings' => '1',
            'usepostcounts' => '1',
            'usethreadcounts' => '1',
            'password' => '',
            'showinjump' => '1',
            'style' => '0',
            'overridestyle' => '0',
            'rulestype' => '0',
            'rulestitle' => '',
            'rules' => '',
        ],
    ],
    'helpdocs' => [
        [
            'hid' => '1',
            'sid' => '1',
            'name' => 'User Registration',
            'description' => 'Perks and privileges to user registration.',
            'document' => 'Some parts of this forum may require you to be logged in and registered. Registration is free and takes a few minutes to complete.<br />
<br />
You are encouraged to register; once you register you will be able to post messages, set your own preferences, and maintain a profile.<br />
<br />
Some of the features that generally require registration are subscriptions, changing of styles, accessing of your Personal Pad (simple notepad) and emailing forum members.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '1',
        ],
        [
            'hid' => '2',
            'sid' => '1',
            'name' => 'Updating Profile',
            'description' => 'Changing your data currently on record.',
            'document' => 'At some point during your stay, you may decide you need to update some information such as your instant messenger information, your password, or perhaps you need to change your email address. You may change any of this information from your user control panel. To access this control panel, simply click on the link in the upper right hand corner of most any page entitled "user cp". From there, simply choose "Edit Profile" and change or update any desired items, then proceed to click the submit button located at the bottom of the page for changes to take effect.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '2',
        ],
        [
            'hid' => '3',
            'sid' => '1',
            'name' => 'Use of Cookies on myBB',
            'description' => 'myBB uses cookies to store certain information about your registration.',
            'document' => 'myBulletinBoard makes use of cookies to store your login information if you are registered, and your last visit if you are not.<br />
<br />
Cookies are small text documents stored on your computer; the cookies set by this forum can only be used on this website and pose no security risk.<br />
<br />
Cookies on this forum also track the specific topics you have read and when you last read them.<br />
<br />
To clear all cookies set by this forum, you can click <a href="misc.php?action=clearcookies&amp;my_post_key={1}">here</a>.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '3',
        ],
        [
            'hid' => '4',
            'sid' => '1',
            'name' => 'Logging In and Out',
            'description' => 'How to login and log out.',
            'document' => 'When you login, you set a cookie on your machine so that you can browse the forums without having to enter in your username and password each time. Logging out clears that cookie to ensure nobody else can browse the forum as you.<br />
<br />
To login, simply click the login link at the top right hand corner of the forum. To log out, click the log out link in the same place. In the event you cannot log out, clearing cookies on your machine will take the same effect.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '4',
        ],
        [
            'hid' => '5',
            'sid' => '2',
            'name' => 'Posting a New Topic',
            'description' => 'Starting a new thread in a forum.',
            'document' => 'When you go to a forum you are interested in and you wish to create a new topic (or thread), simply choose the button at the top and bottom of the forums entitled "New topic". Please take note that you may not have permission to post a new topic in every forum as your administrator may have restricted posting in that forum to staff or archived the forum entirely.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '1',
        ],
        [
            'hid' => '6',
            'sid' => '2',
            'name' => 'Posting a Reply',
            'description' => 'Replying to a topic within a forum.',
            'document' => 'During the course of your visit, you may encounter a thread to which you would like to make a reply. To do so, simply click the "Post reply" button at the bottom or top of the thread. Please take note that your administrator may have restricted posting to certain individuals in that particular forum.<br />
<br />
Additionally, a moderator of a forum may have closed a thread meaning that users cannot reply to it. There is no way for a user to open such a thread without the help of a moderator or administrator.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '2',
        ],
        [
            'hid' => '7',
            'sid' => '2',
            'name' => 'MyCode',
            'description' => 'Learn how to use MyCode to enhance your posts.',
            'document' => 'You can use MyCode, a simplified version of HTML, in your posts to create certain effects.
<p><br />
[b]This text is bold[/b]<br />
&nbsp;&nbsp;&nbsp;<b>This text is bold</b>
<p>
[i]This text is italicized[/i]<br />
&nbsp;&nbsp;&nbsp;<i>This text is italicized</i>
<p>
[u]This text is underlined[/u]<br />
&nbsp;&nbsp;&nbsp;<u>This text is underlined</u>
<p><br />
[url]http://www.example.com/[/url]<br />
&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">http://www.example.com/</a>
<p>
[url=http://www.example.com/]Example.com[/url]<br />
&nbsp;&nbsp;&nbsp;<a href="http://www.example.com/">Example.com</a>
<p>
[email]example@example.com[/email]<br />
&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">example@example.com</a>
<p>
[email=example@example.com]E-mail Me![/email]<br />
&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com">E-mail Me!</a>
<p>
[email=example@example.com?subject=spam]E-mail with subject[/email]<br />
&nbsp;&nbsp;&nbsp;<a href="mailto:example@example.com?subject=spam">E-mail with subject</a>
<p><br />
[quote]Quoted text will be here[/quote]<br />
&nbsp;&nbsp;&nbsp;<quote>Quoted text will be here</quote>
<p>
[code]Text with preserved formatting[/code]<br />
&nbsp;&nbsp;&nbsp;<code>Text with preserved formatting</code>
<p><br />
[img]https://secure.php.net/images/php.gif[/img]<br />
&nbsp;&nbsp;&nbsp;<img src="https://secure.php.net/images/php.gif">
<p>
[img=50x50]https://secure.php.net/images/php.gif[/img]<br />
&nbsp;&nbsp;&nbsp;<img src="https://secure.php.net/images/php.gif" width="50" height="50">
<p><br />
[color=red]This text is red[/color]<br />
&nbsp;&nbsp;&nbsp;<font color="red">This text is red</font>
<p>
[size=3]This text is size 3[/size]<br />
&nbsp;&nbsp;&nbsp;<font size="3">This text is size 3</font>
<p>
[font=Tahoma]This font is Tahoma[/font]<br />
&nbsp;&nbsp;&nbsp;<font face="Tahoma">This font is Tahoma</font>
<p><br />
[align=center]This is centered[/align]<div align="center">This is centered</div>
<p>
[align=right]This is right-aligned[/align]<div align="right">This is right-aligned</div>
<p><br />
[list]<br />
[*]List Item #1<br />
[*]List Item #2<br />
[*]List Item #3<br />
[/list]<br />
<ul>
<li>List item #1</li>
<li>List item #2</li>
<li>List Item #3</li>
</ul><p><font size=1>You can make an ordered list by using [list=1] for a numbered, and [list=a] for an alphabetical list.</font>',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '3',
        ],
    ],
    'helpsections' => [
        [
            'sid' => '1',
            'name' => 'User Maintenance',
            'description' => 'Basic instructions for maintaining a forum account.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '1',
        ],
        [
            'sid' => '2',
            'name' => 'Posting',
            'description' => 'Posting, replying, and basic usage of forum.',
            'usetranslation' => '1',
            'enabled' => '1',
            'disporder' => '2',
        ],
    ],
    'icons' => [
        [
            'iid' => '1',
            'name' => 'Bug',
            'path' => 'images/icons/bug.png',
        ],
        [
            'iid' => '2',
            'name' => 'Exclamation',
            'path' => 'images/icons/exclamation.png',
        ],
        [
            'iid' => '3',
            'name' => 'Question',
            'path' => 'images/icons/question.png',
        ],
        [
            'iid' => '4',
            'name' => 'Smile',
            'path' => 'images/icons/smile.png',
        ],
        [
            'iid' => '5',
            'name' => 'Sad',
            'path' => 'images/icons/sad.png',
        ],
        [
            'iid' => '6',
            'name' => 'Wink',
            'path' => 'images/icons/wink.png',
        ],
        [
            'iid' => '7',
            'name' => 'Big Grin',
            'path' => 'images/icons/biggrin.png',
        ],
        [
            'iid' => '8',
            'name' => 'Tongue',
            'path' => 'images/icons/tongue.png',
        ],
        [
            'iid' => '9',
            'name' => 'Brick',
            'path' => 'images/icons/brick.png',
        ],
        [
            'iid' => '10',
            'name' => 'Heart',
            'path' => 'images/icons/heart.png',
        ],
        [
            'iid' => '11',
            'name' => 'Information',
            'path' => 'images/icons/information.png',
        ],
        [
            'iid' => '12',
            'name' => 'Lightbulb',
            'path' => 'images/icons/lightbulb.png',
        ],
        [
            'iid' => '13',
            'name' => 'Music',
            'path' => 'images/icons/music.png',
        ],
        [
            'iid' => '14',
            'name' => 'Photo',
            'path' => 'images/icons/photo.png',
        ],
        [
            'iid' => '15',
            'name' => 'Rainbow',
            'path' => 'images/icons/rainbow.png',
        ],
        [
            'iid' => '16',
            'name' => 'Shocked',
            'path' => 'images/icons/shocked.png',
        ],
        [
            'iid' => '17',
            'name' => 'Star',
            'path' => 'images/icons/star.png',
        ],
        [
            'iid' => '18',
            'name' => 'Thumbs Down',
            'path' => 'images/icons/thumbsdown.png',
        ],
        [
            'iid' => '19',
            'name' => 'Thumbs Up',
            'path' => 'images/icons/thumbsup.png',
        ],
        [
            'iid' => '20',
            'name' => 'Video',
            'path' => 'images/icons/video.png',
        ],
    ],
    'profilefields' => [
        [
            'fid' => '1',
            'name' => 'Location',
            'description' => 'Where in the world do you live?',
            'disporder' => '1',
            'contact' => '0',
            'type' => 'text',
            'regex' => '',
            'length' => '0',
            'maxlength' => '255',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
        [
            'fid' => '2',
            'name' => 'Bio',
            'description' => 'Enter a few short details about yourself, your life story etc.',
            'disporder' => '2',
            'contact' => '0',
            'type' => 'textarea',
            'regex' => '',
            'length' => '0',
            'maxlength' => '0',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
        [
            'fid' => '3',
            'name' => 'Gender',
            'description' => 'Please select your gender from the list below.',
            'disporder' => '3',
            'contact' => '0',
            'type' => 'select
Undisclosed
Male
Female
Other',
            'regex' => '',
            'length' => '0',
            'maxlength' => '0',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
        [
            'fid' => '4',
            'name' => 'Facebook',
            'description' => 'What is your Facebook username?',
            'disporder' => '1',
            'contact' => '1',
            'type' => 'text',
            'regex' => '',
            'length' => '0',
            'maxlength' => '255',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
        [
            'fid' => '5',
            'name' => 'Twitter',
            'description' => 'What is your Twitter username?',
            'disporder' => '2',
            'contact' => '1',
            'type' => 'text',
            'regex' => '^[a-zA-Z0-9_]+$',
            'length' => '0',
            'maxlength' => '15',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
        [
            'fid' => '6',
            'name' => 'Skype',
            'description' => 'What is your Skype ID?',
            'disporder' => '3',
            'contact' => '1',
            'type' => 'text',
            'regex' => '^[a-zA-Z0-9-_.,@:]+$',
            'length' => '0',
            'maxlength' => '35',
            'required' => '0',
            'registration' => '0',
            'profile' => '1',
            'postbit' => '0',
            'viewableby' => '-1',
            'editableby' => '-1',
            'postnum' => '0',
        ],
    ],
    'questions' => [
        [
            'qid' => '1',
            'question' => 'What does 2 + 2 equal?',
            'answer' => '4
Four',
            'shown' => '0',
            'correct' => '0',
            'incorrect' => '0',
            'active' => '1',
        ],
    ],
    'reportreasons' => [
        [
            'rid' => '1',
            'title' => '<lang:report_reason_other>',
            'appliesto' => 'all',
            'extra' => '1',
            'disporder' => '99',
        ],
        [
            'rid' => '2',
            'title' => '<lang:report_reason_rules>',
            'appliesto' => 'all',
            'extra' => '0',
            'disporder' => '1',
        ],
        [
            'rid' => '3',
            'title' => '<lang:report_reason_bad>',
            'appliesto' => 'all',
            'extra' => '0',
            'disporder' => '2',
        ],
        [
            'rid' => '4',
            'title' => '<lang:report_reason_spam>',
            'appliesto' => 'all',
            'extra' => '0',
            'disporder' => '3',
        ],
        [
            'rid' => '5',
            'title' => '<lang:report_reason_wrong>',
            'appliesto' => 'post',
            'extra' => '0',
            'disporder' => '4',
        ],
    ],
    'smilies' => [
        [
            'sid' => '1',
            'name' => 'Smile',
            'find' => ':)',
            'image' => 'images/smilies/smile.png',
            'disporder' => '1',
            'showclickable' => '1',
        ],
        [
            'sid' => '2',
            'name' => 'Wink',
            'find' => ';)',
            'image' => 'images/smilies/wink.png',
            'disporder' => '2',
            'showclickable' => '1',
        ],
        [
            'sid' => '3',
            'name' => 'Cool',
            'find' => ':cool:',
            'image' => 'images/smilies/cool.png',
            'disporder' => '3',
            'showclickable' => '1',
        ],
        [
            'sid' => '4',
            'name' => 'Big Grin',
            'find' => ':D',
            'image' => 'images/smilies/biggrin.png',
            'disporder' => '4',
            'showclickable' => '1',
        ],
        [
            'sid' => '5',
            'name' => 'Tongue',
            'find' => ':P',
            'image' => 'images/smilies/tongue.png',
            'disporder' => '5',
            'showclickable' => '1',
        ],
        [
            'sid' => '6',
            'name' => 'Rolleyes',
            'find' => ':rolleyes:',
            'image' => 'images/smilies/rolleyes.png',
            'disporder' => '6',
            'showclickable' => '1',
        ],
        [
            'sid' => '7',
            'name' => 'Shy',
            'find' => ':shy:',
            'image' => 'images/smilies/shy.png',
            'disporder' => '7',
            'showclickable' => '1',
        ],
        [
            'sid' => '8',
            'name' => 'Sad',
            'find' => ':(',
            'image' => 'images/smilies/sad.png',
            'disporder' => '8',
            'showclickable' => '1',
        ],
        [
            'sid' => '9',
            'name' => 'At',
            'find' => ':at:',
            'image' => 'images/smilies/at.png',
            'disporder' => '9',
            'showclickable' => '1',
        ],
        [
            'sid' => '10',
            'name' => 'Angel',
            'find' => ':angel:',
            'image' => 'images/smilies/angel.png',
            'disporder' => '10',
            'showclickable' => '1',
        ],
        [
            'sid' => '11',
            'name' => 'Angry',
            'find' => ':@',
            'image' => 'images/smilies/angry.png',
            'disporder' => '11',
            'showclickable' => '1',
        ],
        [
            'sid' => '12',
            'name' => 'Blush',
            'find' => ':blush:',
            'image' => 'images/smilies/blush.png',
            'disporder' => '12',
            'showclickable' => '1',
        ],
        [
            'sid' => '13',
            'name' => 'Confused',
            'find' => ':s',
            'image' => 'images/smilies/confused.png',
            'disporder' => '13',
            'showclickable' => '1',
        ],
        [
            'sid' => '14',
            'name' => 'Dodgy',
            'find' => ':dodgy:',
            'image' => 'images/smilies/dodgy.png',
            'disporder' => '14',
            'showclickable' => '1',
        ],
        [
            'sid' => '15',
            'name' => 'Exclamation',
            'find' => ':exclamation:',
            'image' => 'images/smilies/exclamation.png',
            'disporder' => '15',
            'showclickable' => '1',
        ],
        [
            'sid' => '16',
            'name' => 'Heart',
            'find' => ':heart:',
            'image' => 'images/smilies/heart.png',
            'disporder' => '16',
            'showclickable' => '1',
        ],
        [
            'sid' => '17',
            'name' => 'Huh',
            'find' => ':huh:',
            'image' => 'images/smilies/huh.png',
            'disporder' => '17',
            'showclickable' => '1',
        ],
        [
            'sid' => '18',
            'name' => 'Idea',
            'find' => ':idea:',
            'image' => 'images/smilies/lightbulb.png',
            'disporder' => '18',
            'showclickable' => '1',
        ],
        [
            'sid' => '19',
            'name' => 'Sleepy',
            'find' => ':sleepy:',
            'image' => 'images/smilies/sleepy.png',
            'disporder' => '19',
            'showclickable' => '1',
        ],
        [
            'sid' => '20',
            'name' => 'Undecided',
            'find' => ':-/',
            'image' => 'images/smilies/undecided.png',
            'disporder' => '20',
            'showclickable' => '1',
        ],
        [
            'sid' => '21',
            'name' => 'Cry',
            'find' => ':cry:',
            'image' => 'images/smilies/cry.png',
            'disporder' => '21',
            'showclickable' => '1',
        ],
        [
            'sid' => '22',
            'name' => 'Sick',
            'find' => ':sick:',
            'image' => 'images/smilies/sick.png',
            'disporder' => '22',
            'showclickable' => '1',
        ],
        [
            'sid' => '23',
            'name' => 'Arrow',
            'find' => ':arrow:',
            'image' => 'images/smilies/arrow.png',
            'disporder' => '23',
            'showclickable' => '1',
        ],
        [
            'sid' => '24',
            'name' => 'My',
            'find' => ':my:',
            'image' => 'images/smilies/my.png',
            'disporder' => '24',
            'showclickable' => '1',
        ],
    ],
    'spiders' => [
        [
            'name' => 'Google',
            'useragent' => 'Googlebot',
        ],
        [
            'name' => 'Bing',
            'useragent' => 'bingbot',
        ],
        [
            'name' => 'Alexa Internet',
            'useragent' => 'ia_archiver',
        ],
        [
            'name' => 'Ask.com',
            'useragent' => 'Teoma',
        ],
        [
            'name' => 'Baidu',
            'useragent' => 'Baiduspider',
        ],
        [
            'name' => 'Yandex',
            'useragent' => 'YandexBot',
        ],
        [
            'name' => 'Facebook',
            'useragent' => 'facebookexternalhit',
        ],
        [
            'name' => 'Twitter',
            'useragent' => 'Twitterbot',
        ],
        [
            'name' => 'Internet Archive',
            'useragent' => 'archive.org_bot',
        ],
        [
            'name' => 'Discord',
            'useragent' => 'Discordbot',
        ],
        [
            'name' => 'Applebot',
            'useragent' => 'Applebot',
        ],
        [
            'name' => 'CheckHost',
            'useragent' => 'CheckHost',
        ],
        [
            'name' => 'Pingdom',
            'useragent' => 'Pingdom.com_bot',
        ],
        [
            'name' => 'DuckDuckGo',
            'useragent' => 'DuckDuckBot',
        ],
        [
            'name' => 'UptimeRobot',
            'useragent' => 'UptimeRobot',
        ],
    ],
    'templategroups' => [
        [
            'gid' => '1',
            'prefix' => 'calendar',
            'title' => '<lang:group_calendar>',
            'isdefault' => '1',
        ],
        [
            'gid' => '2',
            'prefix' => 'editpost',
            'title' => '<lang:group_editpost>',
            'isdefault' => '1',
        ],
        [
            'gid' => '3',
            'prefix' => 'forumbit',
            'title' => '<lang:group_forumbit>',
            'isdefault' => '1',
        ],
        [
            'gid' => '4',
            'prefix' => 'forumjump',
            'title' => '<lang:group_forumjump>',
            'isdefault' => '1',
        ],
        [
            'gid' => '5',
            'prefix' => 'forumdisplay',
            'title' => '<lang:group_forumdisplay>',
            'isdefault' => '1',
        ],
        [
            'gid' => '6',
            'prefix' => 'index',
            'title' => '<lang:group_index>',
            'isdefault' => '1',
        ],
        [
            'gid' => '7',
            'prefix' => 'error',
            'title' => '<lang:group_error>',
            'isdefault' => '1',
        ],
        [
            'gid' => '8',
            'prefix' => 'memberlist',
            'title' => '<lang:group_memberlist>',
            'isdefault' => '1',
        ],
        [
            'gid' => '9',
            'prefix' => 'multipage',
            'title' => '<lang:group_multipage>',
            'isdefault' => '1',
        ],
        [
            'gid' => '10',
            'prefix' => 'private',
            'title' => '<lang:group_private>',
            'isdefault' => '1',
        ],
        [
            'gid' => '11',
            'prefix' => 'portal',
            'title' => '<lang:group_portal>',
            'isdefault' => '1',
        ],
        [
            'gid' => '12',
            'prefix' => 'postbit',
            'title' => '<lang:group_postbit>',
            'isdefault' => '1',
        ],
        [
            'gid' => '13',
            'prefix' => 'posticons',
            'title' => '<lang:group_posticons>',
            'isdefault' => '1',
        ],
        [
            'gid' => '14',
            'prefix' => 'showthread',
            'title' => '<lang:group_showthread>',
            'isdefault' => '1',
        ],
        [
            'gid' => '15',
            'prefix' => 'usercp',
            'title' => '<lang:group_usercp>',
            'isdefault' => '1',
        ],
        [
            'gid' => '16',
            'prefix' => 'online',
            'title' => '<lang:group_online>',
            'isdefault' => '1',
        ],
        [
            'gid' => '17',
            'prefix' => 'moderation',
            'title' => '<lang:group_moderation>',
            'isdefault' => '1',
        ],
        [
            'gid' => '18',
            'prefix' => 'nav',
            'title' => '<lang:group_nav>',
            'isdefault' => '1',
        ],
        [
            'gid' => '19',
            'prefix' => 'search',
            'title' => '<lang:group_search>',
            'isdefault' => '1',
        ],
        [
            'gid' => '20',
            'prefix' => 'showteam',
            'title' => '<lang:group_showteam>',
            'isdefault' => '1',
        ],
        [
            'gid' => '21',
            'prefix' => 'reputation',
            'title' => '<lang:group_reputation>',
            'isdefault' => '1',
        ],
        [
            'gid' => '22',
            'prefix' => 'newthread',
            'title' => '<lang:group_newthread>',
            'isdefault' => '1',
        ],
        [
            'gid' => '23',
            'prefix' => 'newreply',
            'title' => '<lang:group_newreply>',
            'isdefault' => '1',
        ],
        [
            'gid' => '24',
            'prefix' => 'member',
            'title' => '<lang:group_member>',
            'isdefault' => '1',
        ],
        [
            'gid' => '25',
            'prefix' => 'warnings',
            'title' => '<lang:group_warning>',
            'isdefault' => '1',
        ],
        [
            'gid' => '26',
            'prefix' => 'global',
            'title' => '<lang:group_global>',
            'isdefault' => '1',
        ],
        [
            'gid' => '27',
            'prefix' => 'header',
            'title' => '<lang:group_header>',
            'isdefault' => '1',
        ],
        [
            'gid' => '28',
            'prefix' => 'managegroup',
            'title' => '<lang:group_managegroup>',
            'isdefault' => '1',
        ],
        [
            'gid' => '29',
            'prefix' => 'misc',
            'title' => '<lang:group_misc>',
            'isdefault' => '1',
        ],
        [
            'gid' => '30',
            'prefix' => 'modcp',
            'title' => '<lang:group_modcp>',
            'isdefault' => '1',
        ],
        [
            'gid' => '31',
            'prefix' => 'announcement',
            'title' => '<lang:group_announcement>',
            'isdefault' => '1',
        ],
        [
            'gid' => '32',
            'prefix' => 'polls',
            'title' => '<lang:group_polls>',
            'isdefault' => '1',
        ],
        [
            'gid' => '33',
            'prefix' => 'post',
            'title' => '<lang:group_post>',
            'isdefault' => '1',
        ],
        [
            'gid' => '34',
            'prefix' => 'printthread',
            'title' => '<lang:group_printthread>',
            'isdefault' => '1',
        ],
        [
            'gid' => '35',
            'prefix' => 'report',
            'title' => '<lang:group_report>',
            'isdefault' => '1',
        ],
        [
            'gid' => '36',
            'prefix' => 'smilieinsert',
            'title' => '<lang:group_smilieinsert>',
            'isdefault' => '1',
        ],
        [
            'gid' => '37',
            'prefix' => 'stats',
            'title' => '<lang:group_stats>',
            'isdefault' => '1',
        ],
        [
            'gid' => '38',
            'prefix' => 'xmlhttp',
            'title' => '<lang:group_xmlhttp>',
            'isdefault' => '1',
        ],
        [
            'gid' => '39',
            'prefix' => 'footer',
            'title' => '<lang:group_footer>',
            'isdefault' => '1',
        ],
        [
            'gid' => '40',
            'prefix' => 'video',
            'title' => '<lang:group_video>',
            'isdefault' => '1',
        ],
        [
            'gid' => '41',
            'prefix' => 'sendthread',
            'title' => '<lang:group_sendthread>',
            'isdefault' => '1',
        ],
        [
            'gid' => '42',
            'prefix' => 'mycode',
            'title' => '<lang:group_mycode>',
            'isdefault' => '1',
        ],
    ],
    'usertitles' => [
        [
            'utid' => '1',
            'posts' => '0',
            'title' => 'Newbie',
            'stars' => '1',
            'starimage' => '',
        ],
        [
            'utid' => '2',
            'posts' => '1',
            'title' => 'Junior Member',
            'stars' => '2',
            'starimage' => '',
        ],
        [
            'utid' => '3',
            'posts' => '50',
            'title' => 'Member',
            'stars' => '3',
            'starimage' => '',
        ],
        [
            'utid' => '4',
            'posts' => '250',
            'title' => 'Senior Member',
            'stars' => '4',
            'starimage' => '',
        ],
        [
            'utid' => '5',
            'posts' => '750',
            'title' => 'Posting Freak',
            'stars' => '5',
            'starimage' => '',
        ],
    ],
];
