<?php
/**
 * MyBB 1.8 English Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

$l['system_email_log'] = "System Email Log";
$l['system_email_log_desc'] = "Any emails which were generated by MyBB and returned an error when being sent are logged by MyBB and are shown below. This section is particularly useful for identifying SMTP configuration issues or for identifying mail support on your server.";
$l['prune_system_email_log'] = "Prune System Email Log";
$l['filter_system_email_log'] = "Filter System Email Log";

$l['close_window'] = "Close Window";
$l['user_email_log_viewer'] = "User Email Log Viewer";
$l['smtp_code'] = "SMTP Code:";
$l['smtp_server_response'] = "SMTP Server Response:";
$l['to'] = "To";
$l['from'] = "From";
$l['subject'] = "Subject";
$l['date'] = "Date";
$l['email'] = "Email";
$l['date_sent'] = "Date Sent";
$l['error_message'] = "Error Message";
$l['find'] = "Find";
$l['no_logs'] = "There are no log entries with the selected criteria.";
$l['subject_contains'] = "Subject contains";
$l['error_message_contains'] = "Error Message contains";
$l['to_address_contains'] = "To Address contains";
$l['from_address_contains'] = "From Address contains";
$l['find_emails_to_addr'] = "Find all emails sent to this address";

