<?php
/**
 * MyBB 1.2
 * Copyright © 2007 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybboard.com
 * License: http://www.mybboard.com/license.php
 *
 * $Id$
 */


function log_admin_action()
{
	global $db, $mybb;

	$log_function = $page->active_module."_admin_log_data";
	if(function_exists($log_function))
	{
		$data = $log_function();
	}
	if(!is_array($data))
	{
		$data = array();
	}

	$log_entry = array(
		"uid" => $mybb->user['uid'],
		"ipaddress" => $db->escape_string(get_ip()),
		"dateline" => time(),
		"module" => $page->active_module,
		"action" => $page->active_action,
		"data" => $db->escape_string(serialize($data))
	);

	$db->insert_query("adminlog2", $log_entry);
}

function admin_redirect($url)
{
	header("Location: $url");
	exit;
}

function update_admin_session($name, $value)
{
	global $db, $admin_session;
	$admin_session['data'][$name] = $value;
	$updated_session = array(
		"data" => $db->escape_string(@serialize($admin_session['data']))
	);
	$db->update_query("adminsessions", $updated_session, "sid='{$admin_session['sid']}'");
}

function flash_message($message, $type='')
{
	$flash = array('message' => $message, 'type' => $type);
	update_admin_session('flash_message', $flash);
}

function rebuild_settings()
{
	global $db, $mybb;
	$query = $db->simple_select("settings", "*", "", array('order_by' => 'title'));
	while($setting = $db->fetch_array($query))
	{
		$setting['value'] = $db->escape_string($setting['value']);
		$settings .= "\$settings['".$setting['name']."'] = \"".$setting['value']."\";\n";
		$mybb->settings[$setting['name']] = $setting['value'];
	}
	$settings = "<?php\n/*********************************\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\*********************************/\n\n$settings\n?>";
	$file = fopen(MYBB_ROOT."inc/settings.php", "w");
	fwrite($file, $settings);
	fclose($file);
	$GLOBALS['settings'] = &$mybb->settings;
}


function draw_admin_pagination($page, $per_page, $total_items, $url)
{
	if($total_items <= $per_page)
	{
		return;
	}

	$pages = ceil($total_items / $per_page);

	$pagination = "<div class=\"pagination\"><span class=\"pages\">Pages: </span>\n";

	if($page > 1)
	{
		$prev = $page-1;
		$prev_page = fetch_page_url($url, $prev);
		$pagination .= "<a href=\"$prev_page\" class=\"previous\">&laquo; Previous</a> \n";
	}

	if($page > 2)
	{
		$from = $page-2;
	}
	else
	{
		$from = $page-1;
	}

	if($from < 1)
	{
		$from = 1;
	}

	if($page == $pages)
	{
		$to = $pages;
	}
	elseif($page == $pages-1)
	{
		$to = $page+1;
	}
	else
	{
		$to = $page+2;
	}

	if($from > 2)
	{
		$first = fetch_page_url($url, 1);
		$pagination .= "<a href=\"{$page_url}\" title=\"Page 1\" class=\"first\">1</a> ... ";
	}

	for($i = $from; $i <= $to; ++$i)
	{
		$page_url = fetch_page_url($url, $i);
		if($page == $i)
		{
			$pagination .= "<span class=\"current\">{$i}</span> \n";
		}
		else
		{
			$pagination .= "<a href=\"{$page_url}\" title=\"Page {$i}\">{$i}</a> \n";
		}
	}

	if($to < $pages)
	{
		$last = fetch_page_url($url, $pages);
		$pagination .= "... <a href=\"{$page_url}\" title=\"Page {$pages}\" class=\"last\">{$pages}</a>";
	}

	if($page < $pages)
	{
		$next = $page+1;
		$next_page = fetch_page_url($url, $next);
		$pagination .= " <a href=\"$next_page\" class=\"next\">Next &raquo;</a>\n";
	}
	$pagination .= "</div>\n";
	return $pagination;
}

?>