<?php

function log_admin_action()
{
	global $db, $mybb;

	$log_function = $page->active_module."_admin_log_data";
	if(function_exists($log_function))
	{
		$data = $log_function();
	}
	if(!is_array($data))
	{
		$data = array();
	}

	$log_entry = array(
		"uid" => $mybb->user['uid'],
		"ipaddress" => $db->escape_string(get_ip()),
		"dateline" => time(),
		"module" => $page->active_module,
		"action" => $page->active_action,
		"data" => $db->escape_string(serialize($data))
	);

	$db->insert_query("adminlog2", $log_entry);
}

function admin_redirect($url)
{
	header("Location: $url");
	exit;
}

function update_admin_session($name, $value)
{
	global $db, $admin_session;
	$admin_session['data'][$name] = $value;
	$updated_session = array(
		"data" => $db->escape_string(@serialize($admin_session['data']))
	);
	$db->update_query("adminsessions", $updated_session, "sid='{$admin_session['sid']}'");
}

function flash_message($message, $type='')
{
	$flash = array('message' => $message, 'type' => $type);
	update_admin_session('flash_message', $flash);
}

function rebuild_settings()
{
	global $db, $mybb;
	$query = $db->query("SELECT * FROM ".TABLE_PREFIX."settings ORDER BY title ASC");
	while($setting = $db->fetch_array($query))
	{
		$setting['value'] = $db->escape_string($setting['value']);
		$settings .= "\$settings['".$setting['name']."'] = \"".$setting['value']."\";\n";
		$mybb->settings[$setting['name']] = $setting['value'];
	}
	$settings = "<?php\n/*********************************\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\*********************************/\n\n$settings\n?>";
	$file = fopen("./inc/settings.php", "w");
	fwrite($file, $settings);
	fclose($file);
	$GLOBALS['settings'] = &$mybb->settings;
}

?>