name: Code Style Check

on: [push, pull_request]

jobs:
    phpcs:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.3'
                tools: cs2pr, phpcs
          - run: phpcs -q --report=checkstyle --standard=phpcs.xml | cs2pr
